# Use the official Flink image as the base image
FROM flink:1.13.0

# Install dependencies
RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y build-essential && \
    apt-get install -y libssl-dev && \
    apt-get install -y zlib1g-dev

# Download and install Python 3.6
RUN wget https://www.python.org/ftp/python/3.6.15/Python-3.6.15.tgz && \
    tar xvf Python-3.6.15.tgz && \
    cd Python-3.6.15 && \
    ./configure --enable-optimizations && \
    make && \
    make install

# Install pip for Python 3.6
RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python3.6 get-pip.py && \
    ln -s /usr/local/bin/pip3.6 /usr/local/bin/pip

# Specify the command to run when the container starts
CMD ["jobmanager"]
