version: '1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  kafka-setup:
    image: wurstmeister/kafka
    container_name: kafka-setup
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      # Wait for Kafka to be ready
      while ! nc -z localhost 9092; do
        sleep 0.1
      done
      # Create topics
      /opt/kafka/bin/kafka-topics.sh --create --topic currency_conversion_output --partitions 1 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181
      /opt/kafka/bin/kafka-topics.sh --create --topic currency_conversion --partitions 1 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181
      "
